version: "3.5"
services:
  app:
    image: node:14-alpine
    container_name: react-criptos
    volumes:
      - ./:/app_criptos
    working_dir: /app_criptos
    ports:
      - 5173:5173
    command: npm start
    tty: true
